model: custom.ECAPATDNN512
nOut: 192
max_frames: 200
batch_size: 256
weight_decay: 2e-5
trainfunc: clova.aamsoftmax
scheduler: onecyclelr
n_mels: 80
log_input: True
max_seg_per_spk: 500
augment_noise: True
augment_specaug: True
save_path: exps/ECAPATDNN512_AAM2