model: clova.ResNetSE34L
nOut: 256
max_frames: 200
batch_size: 256
weight_decay: 2e-5
trainfunc: clova.aamsoftmax
scheduler: onecyclelr
log_input: True
max_seg_per_spk: 500
augment_noise: True
augment_specaug: True
encoder_type: SAP
save_path: exps/ResNetSE34L_AM

